ZhonEdu/urls.py
from django.contrib import admin
from django.urls import path, include
from main import views
from django.contrib.auth.views import LogoutView
from django.conf.urls.static import static
from django.conf import settings
from rest_framework import routers

router = routers.DefaultRouter()
router.register(r'classrooms', views.ClassroomViewSet)
router.register(r'topics', views.TopicViewSet)
router.register(r'tasks', views.TaskViewSet)
router.register(r'classroom-progress', views.ClassroomProgressViewSet)
router.register(r'customs', views.CustomViewSet)

urlpatterns = [
    path('admin/', admin.site.urls),
    path('api/', include(router.urls)),
    path('classroom/', views.classroom_view, name='classroom'),
    path('classrooms/<int:classroom_id>/topics/', views.classroom_topics, name='classroom_topics'),
    path('topics/<int:topic_id>/tasks/', views.topic_tasks, name='topic_tasks'),
    # path('tasks/<int:task_id>/', views.task_text, name='task_text'), 
    path('', views.home_view, name='home'),
    path('library/', views.library_view, name='library'),
    path('login/', views.login_view, name='login'),
    path('registration/', views.registration_view, name='registration'),
    path('logout/', LogoutView.as_view(next_page='/'), name='logout'),
    path('profile/', views.profile_view, name='profile'),
    path('admin_panel/', views.admin_panel, name='admin_panel'),
    path('class_info/', views.class_info, name='class_info'),
    path('class_info/<int:class_id>/edit/', views.edit_class, name='edit_class'),
    path('user_info/', views.user_info, name='user_info'),
    path('topic_info/', views.topic_info, name='topic_info'),
    path('add_topic/', views.add_topic, name='add_topic'),
    path('topic_info/<int:topic_id>/edit/', views.edit_topic, name='edit_topic'),
    path('task_info/', views.task_info, name='task_info'),
    path('add_task/', views.add_task, name='add_task'),
    path('task_info/<int:task_id>/edit/', views.edit_task, name='edit_task'),
    path('get_topics_by_classroom/<int:classroom_id>/', views.get_topics_by_classroom, name='get_topics_by_classroom'),
    path('bookshelf/<int:classroom_id>/', views.bookshelf_view, name='bookshelf'),    
    path('book/<int:topic_id>/images/', views.book_view, name='book'),
    path('topic/<int:topic_id>/videos/', views.video_view, name='video'),
    path('submit_answer/', views.submit_answer, name='submit_answer'),
]   + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

main/models.py
import os
import uuid
from django.db import models
from django.contrib.auth.models import User
from django.conf import settings

def generate_filename(instance, filename):
    extension = filename.split('.')[-1]
    new_filename = f"{uuid.uuid4().hex}.{extension}"
    return os.path.join('profile_pic', new_filename) 


def generate_filename2(instance, filename):
    extension = filename.split('.')[-1]
    new_filename = f"{uuid.uuid4().hex}.{extension}"
    return os.path.join('topic_images', new_filename)


def generate_video_filename(instance, filename):
    extension = filename.split('.')[-1]
    new_filename = f"{uuid.uuid4().hex}.{extension}"
    return os.path.join('topic_videos', new_filename)

# class Task(models.Model):
#     user = models.ForeignKey(User, on_delete=models.CASCADE)
#     name = models.CharField(max_length=100)
#     completed = models.BooleanField(default=False)
#     completion_date = models.DateField()

#     def __str__(self):
#         return self.name

class Classroom(models.Model):
    name = models.CharField(max_length=100)

    def __str__(self):
        return self.name

    @property
    def total_tasks(self):
        return self.task_set.count()

    
class Topic(models.Model):
    name = models.CharField(max_length=100)
    description = models.TextField()
    created_at = models.DateTimeField(auto_now_add=True)
    classroom = models.ForeignKey(Classroom, on_delete=models.CASCADE)
    images = models.ManyToManyField('Image', blank=True)
    videos = models.ManyToManyField('Video', blank=True)

    def __str__(self):
        return self.name
    
class Task(models.Model):
    QUESTION_TYPE_CHOICES = [
        ('MCQ', 'Бірнеше Таңдау Туралы Сұрақ'),
        ('TF', 'Шын / Жалған Сұрақ'),
        ('OQ', 'Ашық Сұрақ'),
    ]

    topic = models.ForeignKey(Topic, on_delete=models.CASCADE, null=True, blank=True)
    classroom = models.ForeignKey(Classroom, on_delete=models.CASCADE, null=True, blank=True)
    question = models.CharField(max_length=255, null=True, blank=True)
    question_type = models.CharField(max_length=10, choices=QUESTION_TYPE_CHOICES, default='MCQ')
    choice1 = models.CharField(max_length=100, blank=True)
    choice2 = models.CharField(max_length=100, blank=True)
    choice3 = models.CharField(max_length=100, blank=True)
    choice4 = models.CharField(max_length=100, blank=True)
    correct_answer = models.CharField(max_length=100, choices=[('choice1', 'Таңдау 1'), ('choice2', 'Таңдау 2'), ('choice3', 'Таңдау 3'), ('choice4', 'Таңдау 4')], null=True, blank=True)

    def __str__(self):
        return self.question
    



    


class ClassroomProgress(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    classroom = models.ForeignKey(Classroom, on_delete=models.CASCADE)
    progress_percentage = models.IntegerField(default=0)
    completed_tasks_count = models.IntegerField(default=0)
    completed_tasks = models.ManyToManyField(Task, related_name='completed_in_classroom')

    def __str__(self):
        return f"{self.user.username} - {self.classroom.name}"
    

class Custom(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    profile_pic = models.ImageField(upload_to=generate_filename, null=True, blank=True, default="profile_pic/default.png")

    # progress_percentage = models.IntegerField(default=0)
    # completed_tasks_count = models.IntegerField(default=0)
    # completed_tasks = models.ManyToManyField(Task, related_name='completed_by')
    # classroom_progress = models.ManyToManyField(ClassroomProgress, related_name='user_progress')

    @property
    def get_name(self):
        return f"{self.user.first_name} {self.user.last_name}"

    @property
    def get_id(self):
        return self.user.id

    def __str__(self):
        return self.user.first_name
    
class Image(models.Model):
    image = models.ImageField(upload_to=generate_filename2, null=True, blank=True)

    def __str__(self):
        return self.image.name

class UserSession(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    login_time = models.DateTimeField(auto_now_add=True)
    logout_time = models.DateTimeField(null=True, blank=True)
    
    def get_session_duration(self):
        if self.logout_time:
            return (self.logout_time - self.login_time).total_seconds() / 60  # duration in minutes
        return 0
    


class Video(models.Model):
    video = models.FileField(upload_to=generate_video_filename, null=True, blank=True)

    def __str__(self):
        return self.video.name

main/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.http import HttpResponseRedirect,HttpResponse
from django.contrib.auth.models import Group
from django.urls import reverse
from django.contrib.auth.forms import AuthenticationForm
from django.contrib.auth import authenticate, login
from django.db.models import Count
from datetime import datetime, timedelta
from .models import *
from .forms import *
from django.contrib.admin.views.decorators import staff_member_required
from django.http import JsonResponse
from django.db.models import F
import logging
from .serializers import *
from rest_framework import viewsets

logger = logging.getLogger(__name__)

def classroom_view(request):
    classrooms = Classroom.objects.order_by('name')
    return render(request, 'classroom.html', {'classrooms': classrooms})

def classroom_topics(request, classroom_id):
    classroom = get_object_or_404(Classroom, pk=classroom_id)
    topics = classroom.topic_set.all()
    return render(request, 'classroom_topics.html', {'classroom': classroom, 'topics': topics})

def topic_tasks(request, topic_id):
    topic = get_object_or_404(Topic, pk=topic_id)
    tasks = topic.task_set.all()
    result = None
    selected_task = None

    if request.method == 'POST':
        task_id = request.POST.get('task_id')
        selected_task = get_object_or_404(Task, pk=task_id)
        
        if selected_task.question_type == 'OQ':
            user_answer = request.POST.get('user_answer')
            if user_answer == selected_task.correct_answer:
                result = 'Correct!'
                if request.user.is_authenticated:
                    handle_correct_answer(request.user, selected_task)
            else:
                result = 'Incorrect!'
        else:
            selected_choice = request.POST.get('choice')
            if selected_choice == selected_task.correct_answer:
                result = 'Correct!'
                if request.user.is_authenticated:
                    handle_correct_answer(request.user, selected_task)
            else:
                result = 'Incorrect!'

    return render(request, 'topic_tasks.html', {
        'topic': topic,
        'tasks': tasks,
        'result': result,
        'selected_task': selected_task
    })

def submit_answer(request):
    if request.method == 'POST':
        task_id = request.POST.get('task_id')
        selected_task = get_object_or_404(Task, pk=task_id)
        result = None
        
        if selected_task.question_type == 'OQ':
            user_answer = request.POST.get('user_answer')
            if user_answer.strip().lower() == selected_task.correct_answer.strip().lower():
                result = 'Дұрыс!'
                if request.user.is_authenticated:
                    handle_correct_answer(request.user, selected_task)
            else:
                result = 'Қате!'
        elif selected_task.question_type == 'MCQ':
            selected_choice = request.POST.get('choice')
            if selected_choice == selected_task.correct_answer:
                result = 'Дұрыс!'
                if request.user.is_authenticated:
                    handle_correct_answer(request.user, selected_task)
            else:
                result = 'Қате!'
        
        return JsonResponse({'result': result})

    return JsonResponse({'result': 'Error'}, status=400)

def handle_correct_answer(user, task):
    # Get or create the Custom object for the user
    custom_user, created = Custom.objects.get_or_create(user=user)
    
    # Get or create the ClassroomProgress for the user and task's classroom
    classroom_progress, created = ClassroomProgress.objects.get_or_create(
        user=user,
        classroom=task.classroom
    )
    
    # Check if the task is already completed by the user in this classroom
    if not classroom_progress.completed_tasks.filter(pk=task.pk).exists():
        # Update the completed tasks count and progress percentage
        classroom_progress.completed_tasks_count += 1
        classroom_progress.progress_percentage = (classroom_progress.completed_tasks_count / task.classroom.topic_set.count()) * 100
        classroom_progress.save()
        
        # Add the task to the completed tasks list
        classroom_progress.completed_tasks.add(task)





def home_view(request):
    profile_pic = None  # По умолчанию нет изображения профиля
    if request.user.is_authenticated:  # Проверка аутентификации пользователя
        try:
            # Получаем объект Custom для текущего пользователя
            custom_profile = Custom.objects.get(user=request.user)
            profile_pic = custom_profile.profile_pic.url if custom_profile.profile_pic else None
        except Custom.DoesNotExist:
            pass  # Профиль Custom отсутствует
    context = {'user': request.user, 'profile_pic': profile_pic}
    return render(request, 'home.html', context)

def library_view(request):
    classrooms = Classroom.objects.order_by('name')
    return render(request, 'library.html', {'classrooms': classrooms})

def login_view(request):
    if request.method == 'POST':
        form = AuthenticationForm(request, data=request.POST)
        if form.is_valid():
            username = form.cleaned_data.get('username')
            password = form.cleaned_data.get('password')
            user = authenticate(request, username=username, password=password)
            if user is not None:
                login(request, user)
                # Перенаправляем пользователя на защищенную страницу
                return redirect('home')  # Укажите имя URL-маршрута для вашей защищенной страницы
    else:
        form = AuthenticationForm()
    return render(request, 'login.html', {'form': form})

from django.contrib.auth.models import Group
from django.shortcuts import render, HttpResponseRedirect, reverse

def registration_view(request):
    if request.method == 'POST':
        userForm = UserForm(request.POST)
        customForm = CustomForm(request.POST, request.FILES)
        if userForm.is_valid() and customForm.is_valid():
            user = userForm.save(commit=False)
            password = userForm.cleaned_data['password']
            user.set_password(password)
            user.save()
            
            custom = customForm.save(commit=False)
            custom.user = user
            custom.save()
            
            # Add user to 'USER' group (create group if it doesn't exist)
            user_group, created = Group.objects.get_or_create(name='USER')
            user.groups.add(user_group)
            
            return HttpResponseRedirect(reverse('login'))
    else:
        userForm = UserForm()
        customForm = CustomForm()
        
    mydict = {'userForm': userForm, 'customForm': customForm}
    return render(request, 'registration.html', context=mydict)

def profile_view(request):
    # Get the user's profile information
    recalculate_all_progress()
    profile_info = Custom.objects.get(user=request.user)
    print("123")
    print(profile_info)
    classroom_progress = ClassroomProgress.objects.filter(user=request.user)
    print(classroom_progress)

    start_date = datetime.now().replace(day=1, hour=0, minute=0, second=0, microsecond=0)
    if start_date.month == 12:
        end_date = start_date.replace(year=start_date.year + 1, month=1, day=1) - timedelta(days=1)
    else:
        end_date = start_date.replace(day=1, month=start_date.month + 1) - timedelta(days=1)

    return render(request, 'profile.html', {'profile_info': profile_info, 'classroom_progress': classroom_progress})

def get_tasks_count_by_date(user, start_date, end_date):
    tasks_count_by_date = Task.objects.filter(
        user=user,
        completed=True,
        completion_date__range=[start_date, end_date]
    ).values('completion_date').annotate(count=Count('id'))

    return tasks_count_by_date




from django.shortcuts import render
from .utils import get_total_time_spent


@staff_member_required(login_url='/')
def admin_panel(request):
    # Получение количества пользователей, задач, классов и тем
    user_count = User.objects.count()
    task_count = Task.objects.count()
    classroom_count = Classroom.objects.count()
    topic_count = Topic.objects.count()

    # Передача данных в шаблон
    return render(request, 'admin_templates/admin_panel.html', {
        'user_count': user_count,
        'task_count': task_count,
        'classroom_count': classroom_count,
        'topic_count': topic_count,
    })

@staff_member_required(login_url='/')
def class_info(request):
    classrooms = Classroom.objects.all()
    form = ClassroomForm()  # Initialize form outside of conditional blocks
    if request.method == 'POST':
        form = ClassroomForm(request.POST)  # Bind form data to form instance
        if 'create_class' in request.POST:
            if form.is_valid():
                form.save()
                return redirect('class_info')
        else:
            class_id = request.POST.get('class_id')
            if 'delete_class' in request.POST and class_id:
                classroom = get_object_or_404(Classroom, pk=class_id)
                classroom.delete()
                return redirect('class_info')
    return render(request, 'admin_templates/class_info.html', {'classrooms': classrooms, 'form': form})
    
@staff_member_required(login_url='/')
def edit_class(request, class_id):
    classroom = get_object_or_404(Classroom, pk=class_id)
    form = ClassroomForm(instance=classroom)
    if request.method == 'POST':
        form = ClassroomForm(request.POST, instance=classroom)
        if form.is_valid():
            form.save()
            return redirect('class_info')
    return render(request, 'admin_templates/edit_class.html', {'form': form, 'classroom': classroom})

@staff_member_required(login_url='/')
def user_info(request):
    users = User.objects.all().order_by('username')
    users_info = []
    for user in users:

main/templates/admin_templates/add_task.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Тапсырма қосу</title>
    {% include 'navbar.html' %}
    <style>
        h1 {
            padding-top: 11vh;
            text-align: center;
            color: white;
            padding-bottom: 1vh;
            position: fixed;
            left: 50%;
            transform: translateX(-50%);
            font-size: 5vh;
            z-index: 1;
        }
    .container-inner{
        padding-top: 20vh;
    }
    #paper {
            color: #FFF;
            display: flex;
            flex-direction: column;
            justify-content: center;
            align-items: center;
        }

        #text {
            background-image:url(https://static.tumblr.com/maopbtg/E9Bmgtoht/lines.png), url(https://static.tumblr.com/maopbtg/nBUmgtogx/paper.png);
            width: 82vh;
            height: auto;
            overflow: hidden;
            background-color: #FFF;
            color: #222;
            font-family: Hombre, monospace;
            font-weight: normal;
            font-size: 24px;
            /* resize: none; */
            line-height: 40px;
            padding: 0px 100px 0px;
            border: 1px solid #FFF;
            /* border-radius: 12px; */
            /* box-shadow: 0px 2px 14px #000; */
            /* margin: 20px; */
        }
        .text-wrapper{
            border-radius: 12px;
            box-shadow: 0px 2px 14px #000;
            margin: 20px;
            overflow: hidden;
            display: flex;
            flex-direction: column;
            /* justify-content: center; */
            /* align-items: center; */
        }

        #title {
            border-bottom: 3px solid #FFF;
            color: #000000;
            font-size: 20px;
            font-family: Hombre, monospace;
            height: 28px;
            font-weight: bold;
            width: 50vh;
        }
        :root {
            --darkgray: #2c3e50;
        }
        select {
        /* Reset Select */
        appearance: none;
        outline: 10px red;
        border: 0;
        box-shadow: none;
        /* Personalize */
        flex: 1;
        padding: 0 1em;
        color: #fff;
        background-color: var(--darkgray);
        background-image: none;
        cursor: pointer;
        font-size:20px;
        font-family:Hombre, monospace;
        }
        /* Remove IE arrow */
        select::-ms-expand {
        display: none;
        }
        /* Custom Select wrapper */
        .select {
        position: relative;
        display: flex;
        width: 20em;
        height: 5vh;
        border-radius: .25em;
        overflow: hidden;
        }
        /* Arrow */
        .select::after {
        content: '\25BC';
        position: absolute;
        top: 0;
        right: 0;
        padding: 1vh;
        background-color: #34495e;
        transition: .25s all ease;
        pointer-events: none;
        }
        /* Transition */
        .select:hover::after {
        color: #f39c12;
        }
        .form-row {
        display: flex;
        justify-content: space-around;
        flex-wrap: wrap;
        width: 80%;
        margin: auto;
        }
        .draw-border {
        box-shadow: inset 0 0 0 4px #58cdd1;
        color: #58afd1;
        -webkit-transition: color 0.25s 0.0833333333s;
        transition: color 0.25s 0.0833333333s;
        position: relative;
        }

        .draw-border::before,
        .draw-border::after {
        border: 0 solid transparent;
        box-sizing: border-box;
        content: '';
        pointer-events: none;
        position: absolute;
        width: 0rem;
        height: 0;
        bottom: 0;
        right: 0;
        }

        .draw-border::before {
        border-bottom-width: 1vh;
        border-left-width: 1vh;
        }

        .draw-border::after {
        border-top-width: 1vh;
        border-right-width: 1vh;
        }

        .draw-border:hover {
        color: #ffcd2c;
        }

        .draw-border:hover::before,
        .draw-border:hover::after {
        border-color: greenyellow;
        -webkit-transition: border-color 0s, width 0.25s, height 0.25s;
        transition: border-color 0s, width 0.25s, height 0.25s;
        width: 100%;
        height: 100%;
        }

        .draw-border:hover::before {
        -webkit-transition-delay: 0s, 0s, 0.25s;
        transition-delay: 0s, 0s, 0.25s;
        }

        .draw-border:hover::after {
        -webkit-transition-delay: 0s, 0.25s, 0s;
        transition-delay: 0s, 0.25s, 0s;
        }

        .btn {
        background: none;
        border: none;
        cursor: pointer;
        font: 700 3vh 'Hombre', sans-serif;
        padding: 1vh 2vh;
        margin: 3vh;
        background-color:  var(--darkgray);
        }

        .btn:focus {
        outline: 2px dotted #55d7dc;
        }
        .cards-wrapper {
        height: 20vh;
        display: flex;
        justify-content: center;
        align-items: flex-start; 
        padding-top: 5vh; 
        overflow-y: auto; 
        }
        .cards {
        display: grid;
        grid-template-columns: 30vh 30vh 30vh;
        grid-gap: 10vh;
        justify-content: center;
        align-items: center;
        /* overflow-y: scroll; */
        }
        .card {
        background-color: #1265a9;
        border-radius: 5px;
        display: flex;
        flex-direction: column;
        align-items: center;
        box-shadow: 0 5px 1px rgb(0, 0, 0, 0.4), inset 3px 5px 1px rgb(255, 255, 255, 0.4);
        color: white;
        padding: 20px;
        z-index: 2;
        &:hover {
                    filter: brightness(1.1); 
                    transform: scale(1.1);
                    cursor: pointer;
                }
        }
    </style>
</head>
<body>
    
    <div class="container">
        
        <h1 style="            padding-top: 11vh;
        text-align: center;
        color: white;
        padding-bottom: 1vh;
        position: fixed;
        left: 50%;
        transform: translateX(-50%);
        font-size: 5vh;
        z-index: 1;">Тапсырма қосу</h1>
        
        <div class="container-inner">
            
            <form method="post" id="paper">
                {% csrf_token %}
                <!-- {{ form.as_p }} -->
                <div class="form-row">
                    <div class="select" id="classroomField">
                        {{ form.classroom }}
                    </div>
                    <div class="select" id="topicField">
                        {{ form.topic }}
                    </div>
                    <div class="select">
                        {{ form.question_type }}
                    </div>
                    <div class="select">
                        {{ form.correct_answer }}
                    </div>
                </div>
                <div class="text-wrapper">
                    <input id="text" type="text" name="question" placeholder="Сұрақ">
                    <input id="text" type="text" name="choice1" maxlength="100" id="id_choice1" placeholder="Бірінші жауап нұсқасы">
                    <input id="text" type="text" name="choice2" maxlength="100" id="id_choice2" placeholder="Екінші жауап нұсқасы">
                    <input id="text" type="text" name="choice3" maxlength="100" id="id_choice3" placeholder="Үшінші жауап нұсқасы">
                    <input id="text" type="text" name="choice4" maxlength="100" id="id_choice4" placeholder="Төртінші жауап нұсқасы">
                </div>
                <button type="submit" name="create_task" class="btn draw-border">Create Task</button>
            </form>
        </div>
    </div>
    </div>
    <script>
    document.addEventListener("DOMContentLoaded", function() {
        const classroomField = document.querySelector(".select#classroomField select");  
        classroomField.addEventListener("change", function() {
            const classroomId = this.value; 
            const topicField = document.querySelector(".select#topicField select");  

            topicField.innerHTML = '';
            fetch(`/get_topics_by_classroom/${classroomId}/`)
                .then(response => response.json())
                .then(data => {
                    data.forEach(topic => {
                        const option = document.createElement("option");
                        option.value = topic.id;
                        option.text = topic.name;
                        topicField.add(option);
                    });
                })
                .catch(error => console.error('Error:', error));
        });
    });

    </script>
</body>
</html>

main/templates/admin_templates/class_info.html
<!-- user_info.html -->
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Сыныптар Тізімі</title>
    {% include 'navbar.html' %}
    <style>
    .cards-wrapper {
    height: 80vh;
    display: flex;
    justify-content: center;
    align-items: flex-start; /* Выравниваем по верху */
    padding-top: 20vh; /* Отступ сверху */
    overflow-y: auto; /* При необходимости добавьте вертикальную прокрутку */
    }

    .cards {
    display: grid;
    grid-template-columns: 30vh 30vh 30vh;
    grid-gap: 10vh;
    justify-content: center;
    align-items: center;
    /* Остальные стили для карточек */
    }

    .card {
    height: 40vh;
    background-color: #1265a9;
    border-radius: 5px;
    display: flex;
    flex-direction: column;
    align-items: center;
    box-shadow: 0 5px 1px rgb(0, 0, 0, 0.4), inset 3px 5px 1px rgb(255, 255, 255, 0.4);
    color: white;
    padding: 20px;
    z-index: 2;
    text-align: center;
    &:hover {
                filter: brightness(1.1); /* Увеличиваем яркость при наведении */
                transform: scale(1.1);
                cursor: pointer;
                /* background-color: #0f4b7d; */
            }
    }
    .card__name {
    margin-top: 1vh;
    font-size: 5vh;
    }

    .card__image {
    height: 20vh;
    width: 20vh;
    border-radius: 50%;
    border: 1vh solid #ffcd2c;
    margin-top: 1vh;
    box-shadow: 0 10px 50px #ffcd2c;
    }
    h1{
    padding-top: 11vh;
    text-align: center; 
    color: white;
    padding-bottom: 1vh;
    position: fixed;
    left: 50%;
    transform: translateX(-50%);
    font-size: 5vh;
    z-index: 1;
    }
    .grid-child{
    text-align: center;
    font-size: 2vh;
    }
    .draw-border {
    box-shadow: inset 0 0 0 4px #58cdd1;
    color: #58afd1;
    -webkit-transition: color 0.25s 0.0833333333s;
    transition: color 0.25s 0.0833333333s;
    position: relative;
    }

    .draw-border::before,
    .draw-border::after {
    border: 0 solid transparent;
    box-sizing: border-box;
    content: '';
    pointer-events: none;
    position: absolute;
    width: 0rem;
    height: 0;
    bottom: 0;
    right: 0;
    }

    .draw-border::before {
    border-bottom-width: 1vh;
    border-left-width: 1vh;
    }

    .draw-border::after {
    border-top-width: 1vh;
    border-right-width: 1vh;
    }

    .draw-border:hover {
    color: #ffcd2c;
    }

    .draw-border:hover::before,
    .draw-border:hover::after {
    border-color: red;
    -webkit-transition: border-color 0s, width 0.25s, height 0.25s;
    transition: border-color 0s, width 0.25s, height 0.25s;
    width: 100%;
    height: 100%;
    }

    .draw-border:hover::before {
    -webkit-transition-delay: 0s, 0s, 0.25s;
    transition-delay: 0s, 0s, 0.25s;
    }

    .draw-border:hover::after {
    -webkit-transition-delay: 0s, 0.25s, 0s;
    transition-delay: 0s, 0.25s, 0s;
    }

    .btn {
    background: none;
    border: none;
    cursor: pointer;
    /* line-height: 1.5; */
    font: 700 3vh 'Hombre', sans-serif;
    padding: 1vh 2vh;
    /* letter-spacing: 0.05rem; */
    margin: 1vh;
    width: 13vh;
    margin-top: 10vh;
    }

    .btn:focus {
    outline: 2px dotted #55d7dc;
    }
    .form-control {
    /* font-size: 3vh;  */
    padding: 10px;
    /* height: 100px; */
    font: 700 2vh 'Hombre', sans-serif;
    border-radius: 30%;
    border: none;
    }
    .card:nth-child(2n){
    background-color: #3088d0;
    }

    </style>
</head>
<body>
    
    <div class="container">
        <h1>Сыныптар Тізімі</h1>
        <div class="cards-wrapper">
        <div class="cards">
            {% for classroom in classrooms %}
            <div class="card">
                <p class="card__name">{{ classroom.name }}</p>
                <form method="post">
                    {% csrf_token %}
                    <input type="hidden" name="class_id" value="{{ classroom.id }}">
                    <button type="submit" name="delete_class" class="btn draw-border">Жою</button>
                </form>
                
            </div>
            {% endfor %}

            <div class="card">
            <form method="post">
                {% csrf_token %}
                <input type="text" name="name" id="id_name" class="form-control" placeholder="Сынып атауын енгізіңіз" required>
                <button type="submit" name="create_class" class="btn draw-border">Сынып қосу</button>
            </form>
            </div>
        
    </div>
    </div>
    </div>
</body>
</html>